In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
b=np.array([2,3,4,5])

In [4]:
a-b

array([-1, -1, -1, -1])

In [5]:
sum=(a-b)**2

In [6]:
sum

array([1, 1, 1, 1], dtype=int32)

In [12]:
np.sum(np.sqrt((a-b)**2)/a.shape)

1.0

In [13]:
a.shape

(4,)

In [14]:
a=np.array([[2,3,4],[1,2,3]])

In [15]:
a.shape

(2, 3)

In [16]:
a.shape[1]

3

In [17]:
a

array([[2, 3, 4],
       [1, 2, 3]])

In [18]:
b=np.array([1,2,3])

In [19]:
b

array([1, 2, 3])

In [20]:
a-b

array([[1, 1, 1],
       [0, 0, 0]])

In [25]:
np.sum((a-b)**2/a.shape[1],axis=1)

array([ 1.,  0.])

In [26]:
  def getNormMatrix(x, lines_num):
    """
    Get a lines_num x size(x, 1) matrix
    """ 
    return np.ones((lines_num, 1)) * np.sum(np.square(x), axis = 1) 

In [27]:
x=a

In [28]:
x

array([[2, 3, 4],
       [1, 2, 3]])

In [30]:
getNormMatrix(x,2)

array([[ 29.,  14.],
       [ 29.,  14.]])

In [31]:
np.sum(np.square(x),axis=1)

array([29, 14], dtype=int32)

In [42]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[2,11,15,5]])

In [43]:
x_train=x

In [44]:
x=np.array([[6,1,7,9],[2,5,6,1]])

In [45]:
num_test=x.shape[0]
num_train=x_train[0]

In [46]:
num_test,num_train

(2, array([1, 2, 3, 4]))

In [47]:
num_train=x_train.shape[0]

In [48]:
num_train

4

In [49]:
getNormMatrix(x, num_train).T

array([[ 167.,  167.,  167.,  167.],
       [  66.,   66.,   66.,   66.]])

In [50]:
getNormMatrix(x_train,num_test)

array([[  30.,  174.,  446.,  375.],
       [  30.,  174.,  446.,  375.]])

In [51]:
np.dot(x, x_train.T)

array([[ 65, 157, 249, 173],
       [ 34,  90, 146, 154]])

In [52]:
#########
fdsf
#######

NameError: name 'fdsf' is not defined

In [53]:
a=[1,2,3]
b=[4,5,6]
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [54]:
np.vstack(a+b)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

IndentationError: unexpected indent (<ipython-input-61-72d9004591fd>, line 8)

In [62]:
 print ('k = %d, accuracy = %f' % (1,2))

k = 1, accuracy = 2.000000


In [63]:
dict={}

In [64]:
dict[a].append(1)

TypeError: unhashable type: 'list'

In [69]:
dict['a']=1

In [71]:
dict.

KeyError: 'b'

In [72]:
a=np.array([1,2,3])

In [73]:
b=np.array([2,3,4])

In [74]:
help(np.stack)

Help on function stack in module numpy.core.shape_base:

stack(arrays, axis=0)
    Join a sequence of arrays along a new axis.
    
    The `axis` parameter specifies the index of the new axis in the dimensions
    of the result. For example, if ``axis=0`` it will be the first dimension
    and if ``axis=-1`` it will be the last dimension.
    
    .. versionadded:: 1.10.0
    
    Parameters
    ----------
    arrays : sequence of array_like
        Each array must have the same shape.
    axis : int, optional
        The axis in the result array along which the input arrays are stacked.
    
    Returns
    -------
    stacked : ndarray
        The stacked array has one more dimension than the input arrays.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis.
    split : Split array into a list of multiple sub-arrays of equal size.
    block : Assemble arrays from blocks.
    
    Examples
    --------
    >>> arrays = [np.random.randn(3,

In [75]:
np.stack((a,b),axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [77]:
a=np.stack((a,b),axis=0)

In [78]:
b=a

In [81]:
np.stack((a,b),axis=-1)

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[2, 2],
        [3, 3],
        [4, 4]]])

In [82]:
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4]])

In [83]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [85]:
c=np.vstack((a,b))

In [86]:
c

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [87]:
cc=c[[0,1,2],[2,1,1]]

In [88]:
cc

array([3, 3, 2])

In [89]:
np.repeat(cc,2)

array([3, 3, 3, 3, 2, 2])

In [94]:
np.repeat(cc.T,10,[3,10])

TypeError: 'list' object cannot be interpreted as an integer

In [95]:
cc

array([3, 3, 2])

In [96]:
np.repeat(cc,10)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2])

In [97]:
np.reshape(np.repeat(cc,10),(3,10))

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [98]:
c

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [99]:
a=[1,1,1,1]

In [101]:
c[np.arange(4),a]

array([2, 3, 2, 3])

In [102]:
a=np.reshape(np.repeat(cc,10),(3,10))

In [103]:
a

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [104]:
a[a>2]=1

In [105]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [106]:
np.sum(a,axis=1)

array([10, 10, 20])