In [1]:
import numpy as np

In [3]:
x=np.array([[2,3,4],[1,2,3]])
p=0.5
mast=(np.random.rand(*x.shape) >= p) / (1 - p)

In [4]:
mast

array([[ 0.,  0.,  2.],
       [ 2.,  0.,  2.]])

In [5]:
x*mast

array([[ 0.,  0.,  8.],
       [ 2.,  0.,  6.]])

In [8]:
pad=1
x

array([[2, 3, 4],
       [1, 2, 3]])

In [9]:
a=np.ones([2,2,2])

In [10]:
a

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

In [13]:
np.pad(a,((0,),(1,),(2,)),mode='constant')

array([[[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]]])

In [14]:
a=np.array([[1,2,3],[2,3,4]])

In [21]:
a[None,None,:]

array([[[[1, 2, 3],
         [2, 3, 4]]]])

In [20]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [22]:
5//2

2

In [23]:
5/2

2.5

In [31]:
mask=np.random.rand(*x.shape) >= p

In [32]:
x

array([[2, 3, 4],
       [1, 2, 3]])

In [33]:
mask

array([[False,  True, False],
       [ True,  True,  True]], dtype=bool)

In [34]:
x*mask

array([[0, 3, 0],
       [1, 2, 3]])